# Generated by Django 5.1 on 2024-09-02 14:08

import Vemora_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vemora_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Vemora_app.models.getfilename),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
