# Generated by Django 5.1 on 2024-09-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vemora_app', '0002_category_image_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Category',
        ),
    ]
