# Generated by Django 5.1 on 2024-09-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vemora_app', '0004_product_delete_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
    ]
