# Generated by Django 5.1 on 2024-09-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vemora_app', '0005_rename_product_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
    ]
